/* =====================================================================
   IXL skills for each Indiana standard (grades 5 and 6).

   Each standard lists IXL skill NAMES. Students type the name into the
   IXL search bar to find the skill. IXL's letter-number codes (like E.7)
   change from year to year, so codes are left for teachers to add in the
   builder, copied from IXL's Indiana (2023) skill plan (links below).

   HOW TO EDIT (no coding needed): change a name between the quotation
   marks, or add one ("Name",) to a standard's list. Keep the commas.
   ===================================================================== */
window.WIN_IXL = {
 plan: {
  math: { "5": "https://www.ixl.com/math/skill-plans/indiana-academic-standards-2023-grade-5",
          "6": "https://www.ixl.com/math/skill-plans/indiana-academic-standards-2023-grade-6" },
  ela:  { "5": "https://www.ixl.com/ela/skill-plans/indiana-academic-standards-2023-grade-5",
          "6": "https://www.ixl.com/ela/skill-plans/indiana-academic-standards-2023-grade-6" }
 },
 skills: {
  /* ---- grade 5 math ---- */
  "5.NS.1": ["Compare fractions", "Compare decimals on number lines", "Put decimal numbers in order"],
  "5.NS.2": ["Fractions as division", "Fractions of a group", "Fractions and mixed numbers"],
  "5.NS.3": ["Multiply by powers of ten", "Divide by powers of ten", "Understand exponents"],
  "5.NS.4": ["What percentage is illustrated?", "Convert between percents, fractions, and decimals", "Percents of numbers"],
  "5.CA.1": ["Divide by two-digit numbers", "Division with remainders", "Estimate quotients"],
  "5.CA.2": ["Division word problems", "Multiplication word problems", "Interpret remainders"],
  "5.CA.3": ["Add and subtract fractions with unlike denominators", "Add and subtract mixed numbers with unlike denominators", "Add fractions with unlike denominators using models"],
  "5.CA.4": ["Add and subtract fractions with unlike denominators: word problems", "Estimate sums and differences of fractions using benchmarks", "Add and subtract mixed numbers: word problems"],
  "5.CA.5": ["Multiply fractions by whole numbers using models", "Multiply two fractions using models", "Multiply two fractions"],
  "5.CA.6": ["Divide unit fractions and whole numbers", "Divide whole numbers by unit fractions using models", "Divide fractions"],
  "5.CA.7": ["Multiply fractions: word problems", "Multiply mixed numbers: word problems", "Multiply fractions by whole numbers: word problems"],
  "5.CA.8": ["Divide unit fractions and whole numbers: word problems", "Divide fractions: word problems", "Divide whole numbers by unit fractions using models"],
  "5.CA.9": ["Add and subtract decimals", "Multiply decimals", "Divide decimals by whole numbers"],
  "5.CA.10": ["Add and subtract money amounts", "Multiply money amounts: word problems", "Divide decimals: word problems"],
  "5.CA.11": ["Graph points on a coordinate plane", "Coordinate planes as maps", "Follow directions on a coordinate plane"],
  "5.G.1": ["Classify triangles", "Acute, right, and obtuse triangles", "Parts of a circle"],
  "5.M.1": ["Convert customary units of length", "Convert metric units", "Convert customary units: word problems"],
  "5.M.2": ["Area of rectangles with fractional side lengths", "Multiply two fractions using models", "Area of rectangles"],
  "5.M.3": ["Area of triangles", "Area of parallelograms", "Area of trapezoids"],
  "5.M.4": ["Volume of rectangular prisms made of unit cubes", "Volume of cubes and rectangular prisms", "Volume of compound figures"],
  "5.M.5": ["Volume of cubes and rectangular prisms", "Volume of cubes and rectangular prisms: word problems", "Volume of compound figures"],
  "5.DA.1": ["Create line plots", "Interpret line plots", "Create and interpret histograms"],
  "5.DA.2": ["Calculate mean, median, mode, and range", "Mean, median, mode, and range: find the missing number", "Interpret charts to find mean, median, mode, and range"],
  /* ---- grade 6 math ---- */
  "6.NS.1": ["Understanding integers", "Integers on number lines", "Graph integers on horizontal and vertical number lines"],
  "6.NS.2": ["Absolute value and opposite integers", "Integers on number lines", "Understanding integers"],
  "6.NS.3": ["Compare and order integers", "Compare rational numbers", "Put rational numbers in order"],
  "6.NS.4": ["Add and subtract fractions: word problems", "Multiply fractions and whole numbers: word problems", "Add, subtract, multiply, and divide decimals: word problems"],
  "6.NS.5": ["Evaluate numerical expressions involving whole numbers", "Evaluate numerical expressions involving decimals", "Evaluate numerical expressions involving fractions"],
  "6.NS.6": ["Greatest common factor", "Least common multiple", "GCF and LCM: word problems"],
  "6.NS.7": ["Identify equivalent expressions", "Write equivalent expressions using properties", "Add and subtract like terms"],
  "6.NS.8": ["Evaluate exponents", "Exponents with decimal and fractional bases", "Write multiplication expressions using exponents"],
  "6.RP.1": ["Convert between percents, fractions, and decimals", "Convert fractions to decimals", "What percentage is illustrated?"],
  "6.RP.2": ["Unit rates", "Unit rates: word problems", "Rate of travel: word problems"],
  "6.RP.3": ["Equivalent ratios", "Ratio tables", "Equivalent ratios: word problems"],
  "6.RP.4": ["Ratios and rates: word problems", "Percents of numbers: word problems", "Solve percent problems using strip models"],
  "6.RP.5": ["Identify independent and dependent variables", "Write a two-variable equation", "Complete a table for a two-variable relationship"],
  "6.AF.1": ["Write variable expressions", "Evaluate variable expressions with whole numbers", "Write variable expressions: word problems"],
  "6.AF.2": ["Does x satisfy the equation?", "Does x satisfy the inequality?", "Which x satisfies an equation?"],
  "6.AF.3": ["Solve one-step equations", "Model and solve one-step equations", "Solve one-step equations: word problems"],
  "6.AF.4": ["Write inequalities from number lines", "Graph inequalities on number lines", "Solutions to inequalities"],
  "6.AF.5": ["Graph points on a coordinate plane", "Objects on a coordinate plane", "Distance between two points"],
  "6.GM.1": ["Convert between metric and customary units", "Convert rates and measurements: customary units", "Convert rates and measurements: metric units"],
  "6.GM.2": ["Find missing angles in triangles", "Find missing angles in quadrilaterals", "Classify triangles"],
  "6.GM.3": ["Area of compound figures", "Area of triangles", "Area of parallelograms"],
  "6.GM.4": ["Volume of cubes and rectangular prisms", "Volume of rectangular prisms with fractional edge lengths", "Volume of compound figures"],
  "6.DS.1": ["Interpret line plots", "Interpret histograms", "Interpret box-and-whisker plots"],
  "6.DS.2": ["Identify statistical questions", "Interpret line plots", "Calculate mean, median, mode, and range"],
  "6.DS.3": ["Calculate mean, median, mode, and range", "Interquartile range", "Mean, median, mode, and range: find the missing number"],
  /* ---- grade 5 ELA ---- */
  "5.RF.1": ["Use Greek and Latin roots as clues to the meanings of words", "Prefixes and suffixes", "Divide words into syllables"],
  "5.RF.2": ["Read and understand informational passages", "Read passages about literature", "Draw inferences from a text"],
  "5.RC.1": ["Draw inferences from a text", "Use text evidence to support a claim", "Read and understand informational passages"],
  "5.RC.2": ["Determine the theme", "Summarize a text", "Determine the themes of short stories"],
  "5.RC.3": ["Identify story elements", "Analyze the structure of a story", "Compare and contrast characters"],
  "5.RC.4": ["Identify the narrative point of view", "Compare accounts of the same event", "Analyze the author's perspective"],
  "5.RC.5": ["Compare stories on similar themes", "Determine the theme", "Compare and contrast characters"],
  "5.RC.6": ["Determine the main idea of a passage", "Identify supporting details", "Summarize a text"],
  "5.RC.7": ["Use text features", "Read and understand informational passages", "Identify text structures"],
  "5.RC.8": ["Identify text structures", "Compare information from two texts", "Identify cause and effect"],
  "5.RC.9": ["Identify supporting details", "Use text evidence to support a claim", "Distinguish facts from opinions"],
  "5.RC.10": ["Compare information from two texts", "Read and understand informational passages", "Identify supporting details"],
  "5.RC.11": ["Determine the meaning of words using context clues", "Use context to identify the meaning of a word", "Use text features"],
  "5.RC.12": ["Synonyms and antonyms", "Multiple-meaning words", "Identify analogies"],
  "5.RC.13": ["Use Greek and Latin roots as clues to the meanings of words", "Determine the meaning of words with Greek and Latin roots", "Prefixes and suffixes"],
  "5.RC.14": ["Identify similes and metaphors", "Interpret figures of speech", "Identify hyperbole"],
  "5.W.1": ["Identify an opinion", "Use text evidence to support a claim", "Transitions with conjunctive adverbs"],
  "5.W.2": ["Choose topic sentences", "Identify supporting details", "Transitions with conjunctive adverbs"],
  "5.W.3": ["Order events in a story", "Use dialogue", "Transitions with conjunctive adverbs"],
  "5.W.4": ["Choose topic sentences", "Transitions with conjunctive adverbs", "Is the sentence a fragment?"],
  "5.W.5": ["Identify supporting details", "Distinguish facts from opinions", "Use text evidence to support a claim"],
  "5.W.6": ["Form and use the perfect verb tenses", "Correlative conjunctions", "Identify prepositional phrases"],
  "5.W.7": ["Commas with introductory elements", "Formatting and punctuating dialogue", "Use apostrophes"],
  "5.CC.1": ["Draw inferences from a text", "Identify supporting details", "Summarize a text"],
  "5.CC.2": ["Draw inferences from a text", "Use text evidence to support a claim", "Identify supporting details"],
  "5.CC.3": ["Summarize a text", "Determine the main idea of a passage", "Identify supporting details"],
  "5.CC.4": ["Determine the main idea of a passage", "Choose topic sentences", "Identify supporting details"],
  "5.CC.5": ["Use text features", "Determine the main idea of a passage", "Identify supporting details"],
  "5.CC.6": ["Distinguish facts from opinions", "Identify supporting details", "Use text evidence to support a claim"],
  "5.CC.7": ["Identify the author's purpose", "Distinguish facts from opinions", "Analyze the author's perspective"],
  /* ---- grade 6 ELA ---- */
  "6.RC.1": ["Draw inferences from a text", "Use text evidence to support a claim", "Read and understand informational passages"],
  "6.RC.2": ["Determine the theme", "Determine the themes of short stories", "Summarize a text"],
  "6.RC.3": ["Analyze the structure of a story", "Identify plot elements", "Read passages about literature"],
  "6.RC.4": ["Compare stories on similar themes", "Compare and contrast characters", "Determine the theme"],
  "6.RC.5": ["Determine the main idea of a passage", "Identify supporting details", "Summarize a text"],
  "6.RC.6": ["Identify text structures", "Identify cause and effect", "Read and understand informational passages"],
  "6.RC.7": ["Identify the author's purpose", "Identify the narrative point of view", "Analyze the author's perspective"],
  "6.RC.8": ["Identify supporting details", "Distinguish facts from opinions", "Use text evidence to support a claim"],
  "6.RC.9": ["Compare information from two texts", "Read and understand informational passages", "Identify text structures"],
  "6.RC.10": ["Determine the meaning of words using context clues", "Use context to identify the meaning of a word", "Multiple-meaning words"],
  "6.RC.11": ["Word relationships", "Use the meanings of words as clues to the meanings of synonyms and antonyms", "Identify analogies"],
  "6.RC.12": ["Positive and negative connotation", "Which word has a more positive or negative connotation?", "Interpret figures of speech"],
  "6.RC.13": ["Use Greek and Latin roots as clues to the meanings of words", "Determine the meaning of words with Greek and Latin roots", "Prefixes and suffixes"],
  "6.W.1": ["Identify a claim", "Use text evidence to support a claim", "Transitions with conjunctive adverbs"],
  "6.W.2": ["Choose topic sentences", "Identify supporting details", "Transitions with conjunctive adverbs"],
  "6.W.3": ["Order events in a story", "Use dialogue", "Transitions with conjunctive adverbs"],
  "6.W.6": ["Pronoun-antecedent agreement", "Is the sentence a fragment?", "Is the sentence a run-on?"],
  "6.W.7": ["Commas with nonrestrictive elements", "Use semicolons", "Use colons"],
  "6.CC.2": ["Draw inferences from a text", "Use text evidence to support a claim", "Identify supporting details"],
  "6.CC.3": ["Summarize a text", "Identify the author's purpose", "Distinguish facts from opinions"],
  "6.W.4": ["Choose topic sentences", "Transitions with conjunctive adverbs", "Is the sentence a run-on?"],
  "6.W.5": ["Identify supporting details", "Distinguish facts from opinions", "Use text evidence to support a claim"],
  "6.CC.1": ["Draw inferences from a text", "Identify supporting details", "Summarize a text"],
  "6.CC.4": ["Compare information from two texts", "Read and understand informational passages", "Identify text structures"],
  "6.CC.5": ["Identify supporting details", "Distinguish facts from opinions", "Use text evidence to support a claim"],
  "6.CC.6": ["Determine the main idea of a passage", "Choose topic sentences", "Identify supporting details"],
  "6.CC.7": ["Determine the main idea of a passage", "Identify supporting details", "Summarize a text"],
  "6.CC.8": ["Distinguish facts from opinions", "Identify the author's purpose", "Use text evidence to support a claim"]
 }
};
