/* =====================================================================
   Small group mini-lessons, shared by the builder (lesson plans) and the
   Resources page (ready-made small group slides).
   Each lesson: [big idea, notes, watch me, try it with me, stop and jot]
   Notes and "try it" use [[answer]] for blanks; {{3 4/5}} draws a number line;
   **word** is bold. In "watch me", line 1 is the problem, then one step per line.
   Math lessons are keyed by the generator name in standards.js (gen), or by
   the standard code; ELA lessons by the grade 6 standard code.
   ===================================================================== */
/* ---------- math mini-lessons ---------- */
const ML={
"6.NS.1":["Positive and negative numbers describe opposite directions. 0 is the starting point.","Above, gaining, and depositing are [[positive]]. Below, losing, and owing are [[negative]]. 0 is the [[starting point|start]].","A diver is 15 feet below sea level. →?\nStep 1: Find the starting point: sea level is 0.\nStep 2: Below sea level is the negative direction.\nStep 3: The diver is at **−15**.","The temperature rose 8 degrees. Which number? [[8|+8]]","Give your own example of a negative number in real life. What does 0 mean in your example?"],
"6.NS.2":["Opposites are the same distance from 0 on opposite sides.","The opposite of 6 is [[−6|-6]]. The opposite of −6 is [[6]]. 0 is its own [[opposite]].","−(−9) = ?\nStep 1: The opposite of 9 is −9.\nStep 2: The opposite of −9 is 9.\nStep 3: So −(−9) = **9**.","−(−4) = [[4]]","Why is the opposite of the opposite of a number the number itself?"],
"6.NS.3":["On a number line, numbers get greater as you move right.","A number to the right is always [[greater|bigger|larger]]. Every negative number is [[less|smaller]] than every positive number.","Order: 3, −7, −2, 5\nStep 1: Negatives come first. −7 is farther left than −2.\nStep 2: Then 3, then 5.\nStep 3: **−7, −2, 3, 5**.","Which is greater, −3 or −8? [[−3|-3]]","Explain why −3 is greater than −8 even though 8 is bigger than 3."],
"6.NS.4":["Read the problem, decide the operation, then estimate to check your answer.","If the problem puts equal groups together, [[multiply]]. If it asks how many groups fit, [[divide]]. Always [[estimate]] first.","Each bag holds 3/4 pound. How much do 4 bags hold?\nStep 1: Equal groups, so multiply: 4 × 3/4.\nStep 2: 4 × 3 = 12, so 12/4.\nStep 3: 12/4 = **3 pounds**. Estimate: 4 bags of almost 1 pound is almost 4. ✓","Pens cost $1.25 each. How much do 4 pens cost? [[5|5.00|$5|$5.00]]","How did estimating help you check your answer?"],
"6.NS.5":["Order of operations: parentheses, exponents, multiply and divide left to right, add and subtract left to right.","Do [[parentheses]] first, then [[exponents]]. Multiply and divide from [[left]] to right.","4 + 3 × 2² = ?\nStep 1: Exponent first: 2² = 4.\nStep 2: Multiply: 3 × 4 = 12.\nStep 3: Add: 4 + 12 = **16**.","6 + 2 × 5 = [[16]]","Why do we all need to follow the same order of operations?"],
"6.NS.6":["The GCF is the greatest factor two numbers share. The LCM is the least multiple they share.","GCF uses [[factors]]. LCM uses [[multiples]].","Rewrite 24 + 36 with the GCF.\nStep 1: Factors of 24 and 36 in common: 1, 2, 3, 4, 6, 12.\nStep 2: The greatest is 12.\nStep 3: 24 + 36 = **12(2 + 3)**.","GCF of 18 and 27: [[9]]","When would you use the LCM in real life?"],
"6.NS.7":["Equivalent expressions are equal for every value of the variable.","The distributive property: 3(x + 2) = 3x + [[6]]. You can only combine [[like]] terms.","Simplify 4(x + 5) + 2x\nStep 1: Distribute: 4x + 20.\nStep 2: Add 2x: 4x + 2x = 6x.\nStep 3: **6x + 20**.","5(n + 3) = 5n + [[15]]","How can you check whether two expressions are equivalent?"],
"6.NS.8":["An exponent tells how many times to multiply the base by itself.","3² means 3 × [[3]]. (1/2)² means 1/2 × [[1/2]].","(2/3)² = ?\nStep 1: Multiply the fraction by itself: 2/3 × 2/3.\nStep 2: Numerators: 2 × 2 = 4. Denominators: 3 × 3 = 9.\nStep 3: **4/9**.","4² = [[16]]","Why is 3² not the same as 3 × 2?"],
"6.RP.1":["Fractions, decimals, and percents are three ways to write the same amount.","Percent means per [[hundred|100]]. To change a decimal to a percent, move the decimal [[two|2]] places right.","Write 3/5 as a percent.\nStep 1: Make the denominator 100: 3/5 = 60/100.\nStep 2: 60 per hundred is 60%.\nStep 3: **3/5 = 0.6 = 60%**.","1/4 = [[25]]%","Which form, fraction, decimal, or percent, is easiest for you? Why?"],
"6.RP.2":["A unit rate tells how much for exactly 1 unit.","To find a unit rate, [[divide]] the total by the number of units. Rate words include [[per]].","12 pencils cost $6. Cost per pencil?\nStep 1: Divide the cost by the number of pencils.\nStep 2: 6 ÷ 12 = 0.5.\nStep 3: **$0.50 per pencil**.","60 miles in 3 hours is [[20]] miles per hour.","Where do you see unit rates in real life?"],
"6.RP.3":["In a ratio table, you multiply or divide both quantities by the same number.","To keep a ratio equivalent, [[multiply]] both numbers by the same amount. Adding the same amount does [[not]] keep the ratio.","2 cups flour : 3 cups sugar. How much sugar for 8 cups flour?\nStep 1: 2 × 4 = 8, so the factor is 4.\nStep 2: 3 × 4 = 12.\nStep 3: **12 cups of sugar**.","3 : 5 = 9 : [[15]]","Why doesn't adding the same number to both parts keep a ratio equivalent?"],
"6.RP.4":["Use a tape diagram, table, or double number line to solve ratio problems.","In a tape diagram, all parts are [[equal]]. Percent is a ratio out of [[100|hundred]].","Boys to girls is 2:3. There are 25 students. How many girls?\nStep 1: Draw 5 equal parts (2 + 3).\nStep 2: 25 ÷ 5 = 5 students per part.\nStep 3: Girls = 3 parts = **15**.","25% of 80 = [[20]]","Which model helps you most for ratio problems? Why?"],
"6.RP.5":["The dependent variable changes because of the independent variable.","In c = 5t, [[c]] is the dependent variable and [[t]] is the independent variable.","Tickets cost $5 each. Write an equation.\nStep 1: Total cost depends on the number of tickets.\nStep 2: Cost = 5 × tickets.\nStep 3: **c = 5t**.","If c = 5t, then when t = 4, c = [[20]]","How can a table help you write an equation?"],
"6.AF.1":["A variable stands for a number. Evaluate by substituting and computing.","3n means 3 [[times|×]] n. \"5 more than\" means [[add]] 5.","Evaluate 4a + b when a = 3, b = 2.\nStep 1: Substitute: 4 × 3 + 2.\nStep 2: Multiply: 12 + 2.\nStep 3: **14**.","2x + 1 when x = 5: [[11]]","Write an expression for a real situation. What does your variable stand for?"],
"6.AF.2":["Substitute each value to see if it makes the equation or inequality true.","A solution makes the statement [[true]]. To check, [[substitute]] the value.","Which makes 3x = 21 true: 6, 7, or 8?\nStep 1: 3 × 6 = 18. No.\nStep 2: 3 × 7 = 21. Yes!\nStep 3: **x = 7**.","Does x = 4 make x + 5 > 8 true? [[yes]]","Why should you always check your answer by substituting?"],
"6.AF.3":["Use inverse operations to get the variable alone.","The inverse of adding is [[subtracting|subtraction]]. The inverse of multiplying is [[dividing|division]].","Solve 4x = 28.\nStep 1: x is multiplied by 4.\nStep 2: Divide both sides by 4.\nStep 3: **x = 7**. Check: 4 × 7 = 28 ✓","x + 9 = 15, x = [[6]]","Why do you do the same thing to both sides of an equation?"],
"6.AF.4":["Inequalities show a range of values. Watch whether the number itself is included.","\"At least\" means [[≥|>=]]. \"No more than\" means [[≤|<=]].","You must be at least 48 inches tall to ride.\nStep 1: At least 48 means 48 or more.\nStep 2: 48 is included, so use ≥.\nStep 3: **h ≥ 48**.","\"Fewer than 10\" uses the symbol [[<]]","Give an example of a rule in your life that could be written as an inequality."],
"6.AF.5":["Points on the same vertical or horizontal line: count the distance, crossing 0 when needed.","The first coordinate is [[x]]. When the signs are different, [[add]] the distances from 0.","Distance from (2, −3) to (2, 4)?\nStep 1: Same x, so count up and down.\nStep 2: −3 to 0 is 3 units. 0 to 4 is 4 units.\nStep 3: 3 + 4 = **7 units**.","Distance from (1, 2) to (6, 2): [[5]]","Why do you add when the points are on opposite sides of 0?"],
"6.GM.1":["Use the conversion factor. Converting to a smaller unit means more of them.","If 1 mile ≈ 1.6 km, then miles to km means [[multiply]]. Km to miles means [[divide]].","1 kg ≈ 2.2 lb. How many pounds is 5 kg?\nStep 1: Each kg is 2.2 lb.\nStep 2: 5 × 2.2 = 11.\nStep 3: **About 11 lb**.","1 inch ≈ 2.5 cm. 4 inches ≈ [[10]] cm","How can you tell if your converted answer should be bigger or smaller?"],
"6.GM.2":["Triangle angles add to 180°. Quadrilateral angles add to 360°.","A triangle's angles add to [[180]]°. A quadrilateral's angles add to [[360]]°.","A triangle has angles 50° and 60°. Third angle?\nStep 1: 50 + 60 = 110.\nStep 2: 180 − 110 = 70.\nStep 3: **70°**.","Angles 90°, 90°, 100° in a quadrilateral. Fourth: [[80]]","Why do you think a quadrilateral's angles add to twice a triangle's?"],
"6.GM.3":["Break a complex shape into rectangles and triangles, then add (or subtract) the areas.","Area of a triangle = base × height ÷ [[2|two]]. For a cut-out corner, [[subtract]] its area.","Rectangle 10 × 4 with a triangle on top (base 10, height 3).\nStep 1: Rectangle: 10 × 4 = 40.\nStep 2: Triangle: 10 × 3 ÷ 2 = 15.\nStep 3: **55 square units**.","Triangle, base 8, height 5: area [[20]]","When would you subtract areas instead of adding them?"],
"6.GM.4":["Volume = length × width × height, even with fraction edges.","V = l × w × [[h]]. Volume is measured in [[cubic]] units.","Box: 4 × 3 × 1/2.\nStep 1: 4 × 3 = 12.\nStep 2: 12 × 1/2 = 6.\nStep 3: **6 cubic units**.","2 × 5 × 1/2 = [[5]]","Why is volume measured in cubic units?"],
"6.DS.1":["Graphs summarize data. A box plot shows five numbers: minimum, Q1, median, Q3, maximum.","The IQR is Q3 minus [[Q1|q1]]. The range is maximum minus [[minimum|min]].","Box plot: 2, 5, 8, 12, 15. Find the IQR.\nStep 1: Q3 = 12, Q1 = 5.\nStep 2: 12 − 5 = 7.\nStep 3: **IQR = 7**.","Box plot 1, 4, 6, 9, 14. IQR = [[5]]","What does a big IQR tell you about the data?"],
"6.DS.2":["A statistical question expects different answers (variability).","\"How old am I?\" is [[not]] statistical. \"How old are students in my school?\" [[is]] statistical.","Is \"How many siblings do my classmates have?\" statistical?\nStep 1: Ask many people.\nStep 2: Expect different answers.\nStep 3: **Yes, it's statistical**.","\"What time is lunch?\" statistical? [[no]]","Write your own statistical question about our class."],
"6.DS.3":["Mean and median describe the center. Range and IQR describe the spread.","To find the median, first put the data in [[order]]. To find the mean, add and then [[divide]].","Data: 7, 3, 9, 5, 6. Find the median.\nStep 1: Order: 3, 5, 6, 7, 9.\nStep 2: The middle value is the 3rd.\nStep 3: **Median = 6**.","Mean of 4, 6, 8: [[6]]","When is the median a better measure than the mean?"]
};
const EL={
"6.RC.1":["Good readers find what the text says AND what it suggests, then prove it with evidence.","An inference is a smart guess based on [[evidence|clues]] and what you already know. You prove it by [[citing|quoting]] the text.","The story says: \"Her lungs burned before she reached the corner.\"\nStep 1: What does the text say? Her lungs burned quickly.\nStep 2: What do I know? Burning lungs mean you're out of breath.\nStep 3: Inference: **Maya is not used to running yet.**","\"He stared at it, his stomach twisting.\" Theo feels [[worried|guilty|nervous|upset]].","What is the difference between what a text says and what it suggests?"],
"6.RC.2":["A theme is a life lesson. Details in the story build it.","A theme is a message about [[life]], not just the topic. A summary should not include [[opinions|opinion]].","Topic: running. What does Maya learn?\nStep 1: What does the character want? To run a full mile.\nStep 2: What changes? She improves one mailbox at a time.\nStep 3: Theme: **Small, steady steps lead to growth.**","The topic is \"mistakes.\" A theme could be: Everyone makes mistakes, but it matters how you [[fix|respond|handle]] them.","How is a theme different from a topic?"],
"6.RC.3":["Every part of a story has a job: to introduce, build, turn, or resolve.","The [[turning point|climax]] is where things change. The [[resolution|ending]] is where the problem is solved.","Why does paragraph 4 of \"The Last Lap\" matter?\nStep 1: What happens? Maya practices for three weeks.\nStep 2: What does it lead to? Tryout day.\nStep 3: Job: **It builds toward the climax.**","A paragraph that introduces the characters is part of the [[exposition|beginning]].","Pick a paragraph. What would the story lose without it?"],
"6.RC.5":["The central idea is what the whole text is mostly about. Details support it.","A detail is [[smaller|narrower]] than the central idea. An objective summary leaves out [[opinions|opinion]].","\"Why Honeybees Dance\"\nStep 1: What is each paragraph about? Problem, direction, distance, research, why it matters.\nStep 2: What connects them all? The dance.\nStep 3: Central idea: **Bees use a dance to share where food is.**","\"Karl von Frisch won the Nobel Prize\" is a [[detail]].","How do you know if an idea is central or just a detail?"],
"6.RC.6":["Authors introduce an idea, then illustrate it with examples and elaborate with more detail.","Authors can introduce ideas with a [[question|problem]], an anecdote, or a fact. Examples [[illustrate|show]] the idea.","How does the bee text introduce the dance?\nStep 1: First sentence: a problem bees have.\nStep 2: Then: bees can't draw or speak.\nStep 3: **The author introduces the dance as the solution to a problem.**","An anecdote is a short [[story]].","Why might an author start with a question?"],
"6.RC.7":["Authors write to inform, persuade, or entertain. Their word choices show their perspective.","Words like \"I believe\" show the author's [[perspective|opinion]]. A text that explains how something works is written to [[inform|explain]].","\"Later Start Times Would Help Students\"\nStep 1: Look for clues: \"I believe schools should start later.\"\nStep 2: The author gives reasons and evidence.\nStep 3: **Purpose: to persuade.**","A story about a dragon is mostly written to [[entertain]].","How can you tell an author's perspective without being told directly?"],
"6.RC.8":["Strong claims are backed by reasons and evidence. Weak claims are not.","A supported claim has [[evidence|facts|a source]]. \"Everyone knows\" usually signals an [[unsupported|opinion]] claim.","Is \"Some schools reported better attendance\" supported?\nStep 1: Is there a fact or source? Yes, schools reported it.\nStep 2: Could we check it? Yes.\nStep 3: **Supported.**","\"Starting later is simply the right thing to do.\" This claim is [[unsupported|not supported]].","What makes evidence convincing?"],
"6.RC.10":["Use the words and sentences around an unknown word to figure out its meaning.","Context clues can be [[examples|definitions|synonyms]] or opposites. Always [[reread|check]] the sentence with your meaning.","\"a good patch of flowers\"\nStep 1: A patch OF flowers.\nStep 2: The bee found it somewhere outside.\nStep 3: **patch = a small area.**","\"Her legs felt like concrete\" means her legs felt [[heavy|tired]].","What do you do when context clues aren't enough?"],
"6.RC.11":["Knowing how two words are related helps you understand both.","A page is [[part]] of a book. An apple is a kind of [[fruit]].","wheel : bicycle\nStep 1: Is a wheel a part of a bicycle? Yes.\nStep 2: So the relationship is part/whole.\nStep 3: **branch : tree** matches.","spark : fire is a [[cause]]/effect relationship.","Make your own part/whole pair."],
"6.RC.12":["Words can mean almost the same thing but carry different feelings.","Connotation is the [[feeling]] a word gives. \"Thrifty\" is [[positive]]; \"cheap\" is negative.","curious vs. nosy\nStep 1: Both mean wanting to know things.\nStep 2: \"Nosy\" suggests being rude.\nStep 3: **curious = positive, nosy = negative.**","\"Confident\" is positive; \"[[arrogant]]\" is negative.","Why do authors choose words carefully?"],
"6.RC.13":["Greek and Latin roots are clues to word meaning.","\"port\" means [[carry]]. \"spect\" means [[look]].","\"spectator\"\nStep 1: Find the root: spect.\nStep 2: spect = look.\nStep 3: **A spectator is a person who watches.**","\"audible\": aud means [[hear]]","List three words with the same root."],
"6.W.6":["Clear sentences use the right pronouns and complete thoughts.","Use \"I\" as a [[subject]] and \"me\" as an object. A fragment is missing a complete [[thought|idea]].","Jamal and ___ went to the store.\nStep 1: Take out \"Jamal and.\"\nStep 2: \"I went\" sounds right; \"me went\" doesn't.\nStep 3: **Jamal and I went to the store.**","\"Because it rained.\" is a [[fragment]]","How can reading a sentence aloud help you find errors?"],
"6.W.7":["Punctuation helps readers understand how ideas connect.","A semicolon joins two complete [[sentences]]. A colon can introduce a [[list]].","The rain stopped ___ we went outside.\nStep 1: \"The rain stopped\" is complete.\nStep 2: \"we went outside\" is complete.\nStep 3: **Use a semicolon: The rain stopped; we went outside.**","Extra information needs commas on [[both]] sides.","When would you use a semicolon instead of a period?"]
};
const ELA_GENERIC=["We will read closely, talk about the text, and write about it using evidence.","Evidence is a [[quote|quotation]] or detail from the text. RACE means Restate, Answer, Cite, [[Explain]].","Restate: turn the question into a sentence.\nAnswer: give your answer.\nCite: quote the text.\nExplain: tell how the quote proves your answer.","Cite means to use [[evidence|a quote]] from the text.","What makes a written answer strong?"];
/* ---------- grade 5 math mini-lessons: big idea, notes, watch me, we do, stop and jot ---------- */
Object.assign(ML,{
"g5-compare":["To compare fractions and decimals, think about where each one sits on a number line.","Numbers farther to the [[right]] are greater. Write decimals with the same number of [[places|digits]] before comparing.","Compare 0.5 and 0.47 →?\nStep 1: Write 0.5 as 0.50.\nStep 2: Compare hundredths: 50 hundredths and 47 hundredths.\nStep 3: **0.5 > 0.47**.","Which is greater, 2/3 or 2/5? [[2/3]]","Why isn't the decimal with more digits always greater?"],
"g5-fracdiv":["A fraction is also a division problem: the numerator divided by the denominator.","3/4 means 3 [[÷|divided by]] 4. When 3 pizzas are shared by 4 people, each gets [[3/4]] of a pizza.","4 friends share 3 sandwiches equally. How much does each get?\nStep 1: Sharing means divide: 3 ÷ 4.\nStep 2: 3 ÷ 4 is the fraction 3/4.\nStep 3: **Each friend gets 3/4 of a sandwich.**","5 ÷ 8 as a fraction: [[5/8]]","Draw a picture to show why 2 ÷ 3 = 2/3."],
"g5-place":["Each place is worth 10 times the place to its right.","Multiplying by 10 moves every digit one place to the [[left]]. Dividing by 10 moves every digit one place to the [[right]].","3.45 × 10 = ?\nStep 1: Each digit moves one place left.\nStep 2: The 3 ones become 3 tens.\nStep 3: **3.45 × 10 = 34.5**.","6.2 ÷ 10 = [[0.62]]","Why doesn't adding a zero to the end of 3.45 multiply it by 10?"],
"g5-round":["Rounding finds the nearest easier number at a place you choose.","Look at the digit to the [[right]] of the rounding place. 5 or more rounds [[up]].","Round 4.372 to the nearest tenth.\nStep 1: The tenths digit is 3.\nStep 2: The digit to its right is 7, which is 5 or more.\nStep 3: **4.372 ≈ 4.4**.","Round 8.649 to the nearest hundredth: [[8.65]]","Why doesn't rounding just mean cutting off digits?"],
"g5-percent":["Percent means \"out of 100.\"","45% means 45 out of [[100]]. 1/2 is the same as [[50]]%.","Write 3/5 as a percent.\nStep 1: Make the denominator 100: multiply by 20.\nStep 2: 3 × 20 = 60, so 60/100.\nStep 3: **3/5 = 60%**.","1/4 = [[25]]%","Where do you see percents outside of school?"],
"g5-divide":["Division splits a number into equal groups. The remainder is what's left over.","The remainder must be [[less|smaller]] than the divisor. Estimate the [[quotient]] first.","Divide 745 ÷ 23.\nStep 1: Estimate: 23 is about 25, and 750 ÷ 25 = 30.\nStep 2: 23 × 32 = 736, and 745 − 736 = 9.\nStep 3: **32 R 9**. 9 is less than 23. ✓","100 ÷ 12 = 8 R [[4]]","In a word problem, how do you decide what to do with the remainder?"],
"g5-decimal":["Decimal operations work like whole numbers. Place value tells where the decimal point goes.","When adding or subtracting, line up the [[decimal points]]. Always [[estimate]] to check.","2.5 + 1.38 = ?\nStep 1: Write 2.5 as 2.50.\nStep 2: Line up the points and add: 2.50 + 1.38.\nStep 3: **3.88**. Estimate: 3 + 1 = 4. ✓","0.4 × 0.2 = [[0.08]]","How does estimating help you place the decimal point?"],
"g5-fracadd":["To add or subtract fractions, the pieces must be the same size first.","Find a common [[denominator]]. Add or subtract only the [[numerators]].","1/2 + 1/3 = ?\nStep 1: A common denominator is 6.\nStep 2: 1/2 = 3/6 and 1/3 = 2/6.\nStep 3: **3/6 + 2/6 = 5/6**. Estimate: ½ + a bit less than ½ is a bit less than 1. ✓","1/4 + 1/2 = [[3/4]]","Why can't you add the denominators?"],
"g5-fracmul":["Multiplying by a fraction finds a part of a group.","2/3 × 3/4 means 2/3 [[of]] 3/4. Multiply the numerators and multiply the [[denominators]].","3 × 2/5 = ?\nStep 1: 3 groups of 2/5.\nStep 2: 3 × 2 = 6, so 6/5.\nStep 3: **6/5 = 1 1/5**.","1/2 × 1/3 = [[1/6]]","Why does multiplying by a fraction less than 1 give a smaller answer?"],
"g5-fracdivide":["Dividing asks how many groups fit, or how big each share is.","4 ÷ 1/3 asks how many [[thirds]] fit in 4. 1/3 ÷ 4 splits one third into [[4]] parts.","3 ÷ 1/4 = ?\nStep 1: How many fourths are in 1 whole? 4.\nStep 2: In 3 wholes: 3 × 4.\nStep 3: **12**.","2 ÷ 1/5 = [[10]]","Draw a model for 1/2 ÷ 3."],
"g5-multiply":["The standard algorithm multiplies by each place, then adds the partial products.","When multiplying by the tens digit, write a [[zero|0]] first. Then [[add]] the partial products.","46 × 23 = ?\nStep 1: 46 × 3 = 138.\nStep 2: 46 × 20 = 920.\nStep 3: **138 + 920 = 1,058**.","32 × 11 = [[352]]","Why do you write a zero before multiplying by the tens digit?"],
"g5-expr":["Parentheses show which step happens first.","In (4 + 5) × 2, you [[add]] first. Without parentheses, multiply before you [[add]].","Write: add 6 and 3, then multiply by 4.\nStep 1: Adding happens first, so it goes in parentheses: (6 + 3).\nStep 2: Then × 4.\nStep 3: **(6 + 3) × 4 = 36**.","(10 − 4) × 3 = [[18]]","How can parentheses change the value of an expression?"],
"g5-shapes":["Shapes belong to families. A shape can have more than one name.","Every square is a [[rectangle]] and a rhombus. A [[trapezoid]] has at least one pair of parallel sides.","Is every rectangle a parallelogram?\nStep 1: A parallelogram needs 2 pairs of parallel sides.\nStep 2: A rectangle has 2 pairs of parallel sides.\nStep 3: **Yes, every rectangle is a parallelogram.**","A triangle with a 90° angle is a [[right]] triangle.","Is every rhombus a square? Explain."],
"g5-coord":["An ordered pair tells how far to move over, then up.","In (3, 5), move 3 to the [[right]], then 5 [[up]].","Plot (4, 2).\nStep 1: Start at (0, 0).\nStep 2: Move 4 right along the x-axis.\nStep 3: **Move 2 up and mark the point.**","(0, 6) is on the [[y]]-axis.","Why does the order of the numbers in (2, 7) matter?"],
"g5-convert":["Converting changes the unit, not the amount.","Big unit to small unit: [[multiply]]. Small unit to big unit: [[divide]].","How many inches are in 4 feet?\nStep 1: 1 foot = 12 inches.\nStep 2: Feet to inches is big to small, so multiply.\nStep 3: **4 × 12 = 48 inches**.","3 meters = [[300]] centimeters","How can you check that your conversion makes sense?"],
"g5-volume":["Volume counts how many unit cubes fill a solid.","V = length × width × [[height]]. Volume is measured in [[cubic]] units.","A box is 4 cm × 3 cm × 2 cm.\nStep 1: One layer: 4 × 3 = 12 cubes.\nStep 2: There are 2 layers.\nStep 3: **12 × 2 = 24 cubic cm**.","5 × 2 × 3 = [[30]] cubic units","How is volume different from area?"],
"g5-area":["Area of a rectangle is length × width, even with fractions.","Area uses [[square]] units. To find it, [[multiply]] the side lengths.","A rectangle is 1/2 ft by 3/4 ft.\nStep 1: Area = 1/2 × 3/4.\nStep 2: Multiply: 3/8.\nStep 3: **3/8 square foot**.","2/3 × 1/2 = [[1/3|2/6]] square unit","Draw a model to show 1/2 × 1/3."],
"g5-lineplot":["A line plot shows how often each value happens. Each X is one data point.","Each X stands for [[one]] measurement. To find a total, [[add]] the values.","Line plot: 1/4, 1/4, 1/2, 3/4, 3/4, 3/4\nStep 1: Count the 3/4 marks: 3.\nStep 2: Total of those: 3 × 3/4.\nStep 3: **9/4 = 2 1/4**.","Three Xs at 1/2 total [[1 1/2|3/2]]","What question could you answer with a line plot of plant heights?"]
});
Object.assign(EL,{
"5.RC.12":["Figurative language says one thing but means another, to paint a picture in your mind.","A simile compares using [[like]] or as. A metaphor says one thing [[is]] another. An idiom doesn't mean what the words say.","\"The hallway was an oven.\"\nStep 1: Is a hallway really an oven? No.\nStep 2: What do ovens have? Heat.\nStep 3: **The hallway was very hot.**","\"as busy as a bee\" is a [[simile]]","Write a simile about today's weather."],
"5.W.6":["Clear writing keeps verb tenses steady and uses the right describing words.","Keep the same [[tense]] unless the time changes. Adverbs like \"quickly\" describe [[verbs|actions]].","Yesterday we ___ (walk) to school.\nStep 1: \"Yesterday\" tells us it's the past.\nStep 2: Past tense of walk: walked.\nStep 3: **Yesterday we walked to school.**","either ... [[or]]","How can reading your writing aloud help you catch tense shifts?"],
"5.W.7":["Punctuation tells readers when to pause and who is speaking.","Use a comma after an [[introductory|opening]] word or phrase. Put spoken words inside [[quotation marks]].","After school ___ we played outside.\nStep 1: \"After school\" introduces the sentence.\nStep 2: Put a comma after it.\nStep 3: **After school, we played outside.**","The cat's toy: the apostrophe shows [[possession|ownership]]","When do you use an apostrophe, and when do you not?"]
});
/* ---------- grade 5 lessons added when the standards were checked against IDOE's documents ---------- */
Object.assign(ML,{
"g5-wholeword":["In a word problem, decide: equal groups means multiply, sharing into groups means divide. Then decide what the remainder means.","If the problem asks how many are needed, a remainder means you [[round up|add one]]. If it asks how many full groups, you [[drop|ignore|leave off]] the remainder.","130 students ride buses that hold 30 each. How many buses?\nStep 1: 130 ÷ 30 = 4 R10.\nStep 2: 10 students still need a seat.\nStep 3: So **5 buses** are needed.","75 cookies go in boxes of 10. How many full boxes? [[7]]","Why does a remainder sometimes mean adding one more, and sometimes mean leaving it off?"],
"g5-triangles":["Triangles are named by their largest angle. Circles are measured from the center.","A right triangle has one [[90]]° angle. An obtuse triangle has one angle [[greater|more|bigger]] than 90°. The diameter is [[2|two]] times the radius.","A triangle has angles of 30°, 50°, and 100°.\nStep 1: Look for a 90° angle. There isn't one.\nStep 2: 100° is more than 90°.\nStep 3: It is an **obtuse triangle**.","A circle has a radius of 6 cm. Its diameter is [[12]] cm.","How can you tell an acute triangle from an obtuse triangle?"],
"g5-polyarea":["Triangles, parallelograms, and trapezoids can all be built from rectangles.","Parallelogram: A = base × [[height]]. Triangle: A = base × height ÷ [[2]]. Trapezoid: add the two bases, multiply by the height, then divide by [[2]].","Triangle: base 8 cm, height 5 cm.\nStep 1: 8 × 5 = 40, the rectangle around the triangle.\nStep 2: The triangle is half of it: 40 ÷ 2 = 20.\nStep 3: A = **20 square cm**.","Parallelogram: base 6 m, height 4 m. A = [[24]] square m","Why do you divide by 2 for a triangle but not for a parallelogram?"],
"g5-center":["Mean, median, and mode each describe a data set in a different way.","The [[median]] is the middle number after you put them in order. The [[mode]] is the value that appears most often.","Find the mean: 4, 6, 7, 7, 6\nStep 1: Add: 4 + 6 + 7 + 7 + 6 = 30.\nStep 2: Count the values: 5.\nStep 3: 30 ÷ 5 = **6**.","Data: 3, 5, 5, 8, 9. The mode is [[5]]. The median is [[5]].","When would the median describe a data set better than the mean?"]
});
/* word-problem standards use the lesson for the same computation */
ML["g5-fracword"]=ML["g5-fracadd"];ML["g5-fracdiv2"]=ML["g5-fracdivide"];ML["g5-fracmulword"]=ML["g5-fracmul"];ML["g5-fracdivword"]=ML["g5-fracdivide"];ML["g5-decimalword"]=ML["g5-decimal"];
window.WIN_LESSONS={math:ML,ela:EL,elaGeneric:ELA_GENERIC};
