/* =====================================================================
   WIN Portal standards list: Indiana Academic Standards (IAS), grades 5 and 6.

   These are the 2023 Indiana Academic Standards, adopted by the State Board
   in June 2023, and checked against IDOE's grade 5 and 6 math and ELA
   documents. They are the standards ILEARN assesses in 2025-26 and 2026-27.
   Official documents: https://www.in.gov/doe/students/indiana-academic-standards/

   HOW TO EDIT (no coding needed):
   - Each standard is one { ... } line group.
       c  = the code, exactly as IDOE writes it (for example "5.CA.3")
       e  = 1 if it is an essential standard, otherwise 0
       s  = short name teachers and students see on the dashboard
       t  = the standard, in brief
       g  = the student learning target, finishing "I can ..."
       gen = which question generator and lesson the builder uses for it.
             Leave gen alone if you only change c, s, t, or g.
       alt = 1 when the standard borrows another standard's questions
             (writing process, research, speaking, listening).
   - Keep the commas and quotation marks. Save, then refresh the builder.
   ===================================================================== */
window.WIN_STANDARDS = {
 framework: "Indiana Academic Standards (2023)",
 /* Set review to a note when a grade's list needs checking against IDOE's documents. */
 review: {
  "5": "",
  "6": ""
 },
 grades: {
 "5": {
  math:[
   {c:"5.NS.1", e:1, gen:"g5-compare", s:"Compare fractions and decimals",
    t:"Use a number line to compare and order fractions, mixed numbers, and decimals to thousandths. Write the results using >, =, and < symbols.",
    g:"compare and order fractions, mixed numbers, and decimals on a number line"},
   {c:"5.NS.2", e:0, gen:"g5-fracdiv", s:"Meanings of fractions",
    t:"Explain different interpretations of fractions, including as parts of a whole, parts of a set, and division of whole numbers by whole numbers.",
    g:"explain a fraction as part of a whole, part of a set, or division"},
   {c:"5.NS.3", e:0, gen:"g5-place", s:"Powers of 10",
    t:"Explain patterns in the number of zeros of the product when multiplying a number by powers of 10, and explain patterns in the placement of the decimal point when a decimal is multiplied or divided by a power of 10. Use whole-number exponents to denote powers of 10.",
    g:"explain patterns when I multiply and divide by powers of 10"},
   {c:"5.NS.4", e:0, gen:"g5-percent", s:"Percents as parts of 100",
    t:"Model percents as parts of 100 using pictures or diagrams and identify the equivalent fraction.",
    g:"model a percent as part of 100 and name the equivalent fraction"},
   {c:"5.CA.1", e:1, gen:"g5-divide", s:"Dividing whole numbers",
    t:"Find whole-number quotients and remainders with up to four-digit dividends and two-digit divisors using strategies based on place value, the properties of operations, and/or the relationship between multiplication and division. Describe the strategy and explain the reasoning used.",
    g:"divide whole numbers and explain my strategy"},
   {c:"5.CA.2", e:1, gen:"g5-wholeword", s:"Multiplication and division word problems",
    t:"Solve real-world problems involving multiplication and division of whole numbers (e.g., by using equations to represent the problem). In division problems that involve a remainder, explain how the remainder affects the solution to the problem.",
    g:"solve multiplication and division word problems and explain what a remainder means"},
   {c:"5.CA.3", e:0, gen:"g5-fracadd", s:"Adding and subtracting fractions",
    t:"Add and subtract fractions and mixed numbers with unlike denominators using strategies or the standard algorithm.",
    g:"add and subtract fractions and mixed numbers with unlike denominators"},
   {c:"5.CA.4", e:1, gen:"g5-fracword", s:"Fraction word problems",
    t:"Solve real-world problems involving addition and subtraction of fractions referring to the same whole, including cases of unlike denominators (e.g., by using visual fraction models and equations to represent the problem). Use benchmark fractions and number sense of fractions to estimate mentally and assess whether the answer is reasonable.",
    g:"solve fraction word problems and check that my answer is reasonable"},
   {c:"5.CA.5", e:1, gen:"g5-fracmul", s:"Multiplying fractions",
    t:"Use visual fraction models to multiply a fraction by a fraction or a whole number.",
    g:"multiply a fraction by a fraction or a whole number using models"},
   {c:"5.CA.6", e:1, gen:"g5-fracdiv2", s:"Dividing fractions",
    t:"Use visual fraction models and numbers to divide a fraction by a fraction or a whole number.",
    g:"divide a fraction by a fraction or a whole number using models"},
   {c:"5.CA.7", e:1, gen:"g5-fracmulword", s:"Fraction multiplication problems",
    t:"Solve real-world problems involving multiplication of fractions, including mixed numbers (e.g., by using visual fraction models and equations to represent the problem).",
    g:"solve word problems that multiply fractions and mixed numbers"},
   {c:"5.CA.8", e:1, gen:"g5-fracdivword", s:"Fraction division problems",
    t:"Solve real-world problems involving division of fractions and mixed numbers (e.g., by using visual fraction models and equations to represent the problem).",
    g:"solve word problems that divide fractions"},
   {c:"5.CA.9", e:0, gen:"g5-decimal", s:"Decimal operations",
    t:"Add, subtract, multiply, and divide decimals to hundredths, using models or drawings and strategies based on place value or the properties of operations. Describe the strategy and explain the reasoning.",
    g:"add, subtract, multiply, and divide decimals and explain my strategy"},
   {c:"5.CA.10", e:1, gen:"g5-decimalword", s:"Decimal and money problems",
    t:"Solve real-world problems involving addition, subtraction, multiplication, and division with decimals to hundredths including problems that involve money in decimal notation (e.g., by using equations, models or drawings, and strategies based on place value or properties of operations to represent the problem).",
    g:"solve real-world problems with decimals and money"},
   {c:"5.CA.11", e:0, gen:"g5-coord", s:"Coordinate grid",
    t:"Represent real-world problems and equations by graphing ordered pairs in the first quadrant of the coordinate plane, and interpret coordinate values of points in the context of the situation.",
    g:"graph ordered pairs and explain what they mean in a situation"},
   {c:"5.G.1", e:0, gen:"g5-triangles", s:"Triangles and circles",
    t:"Identify, describe, and draw triangles (right, acute, obtuse) and circles using appropriate tools (e.g., ruler or straightedge, compass, and technology). Define and model the relationship between radius and diameter.",
    g:"name triangles by their angles and explain how a circle's radius and diameter are related"},
   {c:"5.M.1", e:0, gen:"g5-convert", s:"Converting units",
    t:"Convert among different-sized standard measurement units within a given measurement system and use these conversions in solving multi-step, real-world problems.",
    g:"convert units to solve multi-step problems"},
   {c:"5.M.2", e:0, gen:"g5-area", s:"Area with fractions",
    t:"Find the area of a rectangle with fractional side lengths by modeling with unit squares of the appropriate unit fraction side lengths, and show that the area is the same as would be found by multiplying the side lengths. Multiply fractional side lengths to find areas of rectangles, and represent fraction products as rectangular areas.",
    g:"find the area of rectangles with fraction side lengths"},
   {c:"5.M.3", e:1, gen:"g5-polyarea", s:"Area of triangles and parallelograms",
    t:"Develop and use formulas for the area of triangles, parallelograms, and trapezoids. Solve real-world and other mathematical problems that involve perimeter and area of triangles, parallelograms, and trapezoids, using appropriate units for measures.",
    g:"find the area of triangles, parallelograms, and trapezoids"},
   {c:"5.M.4", e:1, gen:"g5-volume", s:"Volume with unit cubes",
    t:"Find the volume of a right rectangular prism with whole-number side lengths by packing it with unit cubes, and show that the volume is the same as would be found by multiplying the edge lengths or multiplying the height by the area of the base.",
    g:"find the volume of a rectangular prism by counting unit cubes"},
   {c:"5.M.5", e:1, gen:"g5-volume", s:"Volume formulas",
    t:"Apply the formulas V = l × w × h and V = B × h for right rectangular prisms to find volumes of right rectangular prisms with whole-number edge lengths to solve real-world problems and other mathematical problems.",
    g:"use V = l × w × h and V = B × h to solve volume problems"},
   {c:"5.DA.1", e:1, gen:"g5-lineplot", s:"Graphing data",
    t:"Formulate questions that can be addressed with categorical and numerical data and make predictions about the data. Collect, organize, and graph data from observations, surveys, and experiments using line plots with fractional intervals, histograms, or other graphical representations that appropriately represent the data set.",
    g:"show data on line plots and other graphs and answer questions with it"},
   {c:"5.DA.2", e:1, gen:"g5-center", s:"Mean, median, and mode",
    t:"Calculate measures of central tendency (mean, median, and mode) to describe a data set. Analyze data sets to determine which measure of central tendency appropriately describes the distribution of data.",
    g:"find the mean, median, and mode of a data set"}
  ],
  ela:[
   {c:"5.RF.1", e:1, gen:"6.RC.13", alt:1, s:"Reading multisyllabic words",
    t:"Use knowledge of all letter-sound correspondences, syllabication patterns, and morphology (e.g., roots and affixes) to accurately read unfamiliar, multisyllabic words in context.",
    g:"use syllables, roots, and affixes to read long, unfamiliar words"},
   {c:"5.RF.2", e:0, gen:"6.RC.1", alt:1, s:"Reading fluency",
    t:"Orally read grade-level appropriate or higher texts smoothly and accurately, with expression that connotes comprehension.",
    g:"read grade-level text smoothly, accurately, and with expression"},
   {c:"5.RC.1", e:1, gen:"6.RC.1", s:"Quoting to explain",
    t:"Quote accurately from a text when explaining what a text says explicitly and when drawing inferences from the text.",
    g:"quote the text to explain what it says and what it suggests"},
   {c:"5.RC.2", e:1, gen:"6.RC.2", s:"Theme and summary",
    t:"Determine the theme of a story, play, or poem from details in the text, including how characters respond to challenges or how the speaker in a poem reflects upon a topic; summarize the text.",
    g:"find a theme using details and summarize the text"},
   {c:"5.RC.3", e:0, gen:"6.RC.3", s:"Characters, settings, and events",
    t:"Describe two or more characters, settings, or events in a story or play, drawing on specific details in the text and how they impact the plot.",
    g:"describe characters, settings, or events and how they affect the plot"},
   {c:"5.RC.4", e:0, gen:"6.RC.7", s:"Point of view",
    t:"Describe how a narrator's or speaker's point of view influences how events are portrayed.",
    g:"explain how the narrator's point of view shapes how events are told"},
   {c:"5.RC.5", e:0, gen:"6.RC.4", s:"Comparing stories",
    t:"Compare and contrast stories in the same genre on their approaches to similar themes and topics.",
    g:"compare how stories in the same genre handle a similar theme"},
   {c:"5.RC.6", e:1, gen:"6.RC.5", s:"Main ideas",
    t:"Determine two or more main ideas of a text and explain how they are supported by key details; summarize the text.",
    g:"find the main ideas of a text, explain the key details, and summarize it"},
   {c:"5.RC.7", e:0, gen:"6.RC.9", s:"Text features",
    t:"Apply knowledge of text features in multiple print and digital sources to locate information, gain meaning from a text, or solve a problem.",
    g:"use text features to find information and understand a text"},
   {c:"5.RC.8", e:1, gen:"6.RC.6", s:"Text structure",
    t:"Compare and contrast the organizational structure of events, ideas, concepts, or information in two or more texts.",
    g:"compare how two texts are organized"},
   {c:"5.RC.9", e:1, gen:"6.RC.8", s:"Reasons and evidence",
    t:"Explain how an author uses reasons and evidence to support claims in a text, identifying which reasons and evidence support which claims.",
    g:"explain which reasons and evidence support each claim"},
   {c:"5.RC.10", e:0, gen:"6.RC.9", alt:1, s:"Combining sources",
    t:"Combine information from several texts or digital sources on the same topic in order to demonstrate knowledge about the subject.",
    g:"combine information from several texts on the same topic"},
   {c:"5.RC.11", e:0, gen:"6.RC.10", s:"Context clues",
    t:"Select and apply context clues (e.g., word, phrase, sentence, and paragraph clues) and text features to determine the meanings of unknown words.",
    g:"use context clues and text features to figure out word meanings"},
   {c:"5.RC.12", e:0, gen:"6.RC.11", s:"Word relationships",
    t:"Identify relationships among words, including multiple meanings, synonyms and antonyms, homographs, metaphors, similes, and analogies.",
    g:"identify how words are related, like synonyms, antonyms, and analogies"},
   {c:"5.RC.13", e:1, gen:"6.RC.13", s:"Roots and affixes",
    t:"Apply knowledge of word structure elements, known words, and word patterns to determine meaning (e.g., word origins, common Greek and Latin affixes and roots, parts of speech).",
    g:"use Greek and Latin roots and affixes to figure out word meanings"},
   {c:"5.RC.14", e:0, gen:"5.RC.12", s:"Figurative language",
    t:"Determine how words and phrases provide meaning to works of literature, including imagery, symbolism, and figurative language (e.g., similes, metaphors, hyperbole, or allusion).",
    g:"explain what imagery and figurative language add to a story or poem"},
   {c:"5.W.1", e:1, gen:"6.W.1", s:"Persuasive writing",
    t:"Write persuasive compositions in a variety of forms that clearly present a position in an introductory statement to an identified audience; support the position with qualitative and quantitative facts and details from various sources, including texts; use an organizational structure to group related ideas; use language appropriate for the audience; connect reasons to the position using words, phrases, and clauses; and provide a concluding statement or section.",
    g:"write a persuasive piece that supports a position with reasons and facts"},
   {c:"5.W.2", e:1, gen:"6.W.2", s:"Informative writing",
    t:"Write informative compositions on a variety of topics that introduce a topic and organize it logically; employ sufficient examples, facts, quotations, or other information from various sources; connect ideas using transition words; include text features and multimedia when useful; use appropriate language, vocabulary, and sentence variety; and provide a concluding statement or section.",
    g:"explain a topic with facts, examples, and quotations from texts"},
   {c:"5.W.3", e:1, gen:"6.W.3", s:"Narrative writing",
    t:"Write narrative compositions in a variety of forms that develop the exposition; develop an event sequence that unfolds naturally, using transitions; use narrative techniques such as dialogue, description, and pacing; use precise and expressive vocabulary and figurative language; and provide an ending that follows from the events.",
    g:"write a narrative with dialogue, description, and a clear sequence of events"},
   {c:"5.W.4", e:0, gen:"6.W.2", alt:1, s:"Writing process",
    t:"Apply the writing process to generate a draft by developing, selecting, and organizing ideas; revise to improve writing; edit for format and standard English conventions; and use technology to interact and collaborate with others to publish legible documents.",
    g:"plan, draft, revise, and edit my writing"},
   {c:"5.W.5", e:1, gen:"6.W.2", alt:1, s:"Research",
    t:"Conduct research assignments and tasks on a topic: with support, formulate a research question; identify and acquire information through reliable primary and secondary sources; summarize and paraphrase important ideas and details, including direct quotations and citing the source; avoid plagiarism; and present the research information.",
    g:"research a question using reliable sources and share what I learn"},
   {c:"5.W.6", e:1, gen:"5.W.6", s:"Grammar and usage",
    t:"Demonstrate command of English grammar and usage, focusing on verbs (perfect verb tenses; commonly misused verbs such as lie/lay, sit/set, rise/raise), prepositional phrases and their functions, and simple, compound, and complex sentences of all four types, using correlative conjunctions (e.g., either/or, neither/nor).",
    g:"use verb tenses, prepositions, and conjunctions correctly in sentences"},
   {c:"5.W.7", e:1, gen:"5.W.7", s:"Capitalization, punctuation, and spelling",
    t:"Demonstrate command of capitalization, punctuation, and spelling, focusing on correct capitalization; apostrophes and quotation marks; commas for appositives, to set off yes and no, to set off a tag question, and to indicate direct address; and correct spelling patterns and generalizations.",
    g:"use capital letters, apostrophes, quotation marks, and commas correctly"},
   {c:"5.CC.1", e:1, gen:"6.CC.2", alt:1, s:"Collaborative discussions",
    t:"Engage effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) on grade-appropriate topics and texts, building on others' ideas and expressing personal ideas clearly.",
    g:"take part in discussions, build on others' ideas, and share my ideas clearly"},
   {c:"5.CC.2", e:1, gen:"6.CC.2", s:"Questions and comments",
    t:"Pose and respond to specific questions by making comments that contribute to the discussion and elaborate on the remarks of others.",
    g:"ask and answer questions that add to a discussion"},
   {c:"5.CC.3", e:1, gen:"6.CC.3", s:"Summarizing what I hear",
    t:"Orally summarize or respond to a written text read aloud or information presented in diverse media and formats, including visually, quantitatively, and orally.",
    g:"summarize a text or information presented in different formats"},
   {c:"5.CC.4", e:1, gen:"6.CC.3", alt:1, s:"Presenting",
    t:"Use appropriate language to present on a topic or text, or provide a narrative or opinion that organizes ideas appropriately using effective introductions and conclusions. Use appropriate structure, facts, and relevant, descriptive details to support main ideas or themes, speaking at an understandable pace and in a clear and concise manner.",
    g:"present on a topic with a clear introduction, details, and conclusion"},
   {c:"5.CC.5", e:0, gen:"6.W.2", alt:1, s:"Multimedia presentations",
    t:"Create engaging presentations that include multimedia components and visual displays when appropriate to enhance the development of main ideas or themes.",
    g:"add multimedia and visuals that support my main ideas"},
   {c:"5.CC.6", e:0, gen:"6.RC.8", alt:1, s:"Evaluating media claims",
    t:"Review claims made in various types of media and evaluate evidence used to support these claims.",
    g:"evaluate the evidence behind claims in media"},
   {c:"5.CC.7", e:1, gen:"6.RC.7", alt:1, s:"The role of media",
    t:"Identify the role of the media in focusing people's attention on events and in forming their opinions on issues.",
    g:"explain how media shapes what people notice and think"}
  ]
 },
 "6": {
  math:[
   {c:"6.NS.1", e:1, s:"Positive and negative numbers",
    t:"Use positive and negative numbers to represent and compare quantities in real-world contexts, explaining the meaning of 0 in each situation.",
    g:"use positive and negative numbers to describe real-world situations and explain what 0 means"},
   {c:"6.NS.2", e:0, s:"Opposites",
    t:"Explain how opposite signs of numbers indicate locations on opposite sides of 0 on the number line; identify the opposite of the opposite of a number.",
    g:"find opposites and explain where they sit on a number line"},
   {c:"6.NS.3", e:0, s:"Comparing rational numbers",
    t:"Compare and order rational numbers and plot them on a number line. Write, interpret, and explain statements of order for rational numbers in real-world contexts.",
    g:"compare, order, and plot rational numbers on a number line"},
   {c:"6.NS.4", e:1, s:"Fraction and decimal problems",
    t:"Solve real-world problems with positive fractions and decimals by using one or two operations.",
    g:"solve real-world problems with fractions and decimals"},
   {c:"6.NS.5", e:1, s:"Order of operations",
    t:"Apply the order of operations and properties of operations (i.e., identity, inverse, commutative properties of addition and multiplication, associative properties of addition and multiplication, and distributive property) to evaluate numerical expressions with nonnegative rational numbers, including those using grouping symbols, such as parentheses, and involving whole number exponents.",
    g:"use the order of operations to evaluate expressions"},
   {c:"6.NS.6", e:0, s:"GCF and LCM",
    t:"Find the greatest common factor of two whole numbers less than or equal to 100 and the least common multiple of two whole numbers less than or equal to 12. Use the distributive property to express a sum of two whole numbers from 1 to 100, with a common factor as a multiple of a sum of two whole numbers with no common factor.",
    g:"find the GCF and LCM and use the distributive property"},
   {c:"6.NS.7", e:1, s:"Equivalent expressions",
    t:"Apply the properties of operations (i.e., identity, inverse, commutative, associative, distributive properties) to create equivalent linear expressions and to justify whether two linear expressions are equivalent when the two expressions name the same number regardless of which value is substituted into them.",
    g:"write and check equivalent expressions"},
   {c:"6.NS.8", e:0, s:"Exponents",
    t:"Evaluate positive rational numbers with whole number exponents.",
    g:"evaluate numbers with exponents"},
   {c:"6.RP.1", e:1, s:"Fractions, decimals, percents",
    t:"Convert between any two representations (fractions, decimals, percents) of positive rational numbers without the use of a calculator.",
    g:"convert between fractions, decimals, and percents without a calculator"},
   {c:"6.RP.2", e:0, s:"Unit rates",
    t:"Understand the concept of a unit rate and use terms related to rate in the context of a ratio relationship.",
    g:"find and explain unit rates"},
   {c:"6.RP.3", e:0, s:"Ratio tables",
    t:"Make tables of equivalent ratios relating quantities with whole-number measurements, find missing values in the tables, and plot the pairs of values on the coordinate plane.",
    g:"complete tables of equivalent ratios and plot the pairs"},
   {c:"6.RP.4", e:1, s:"Ratio and rate problems",
    t:"Solve real-world and other mathematical problems involving rates and ratios using models and strategies such as reasoning about tables of equivalent ratios, tape diagrams, double number line diagrams, or equations.",
    g:"solve ratio and rate problems with tables, tape diagrams, and equations"},
   {c:"6.RP.5", e:1, s:"Dependent and independent variables",
    t:"Use variables to represent two quantities in a proportional relationship in a real-world problem; write an equation to express one quantity, the dependent variable, in terms of the other quantity, the independent variable. Analyze the relationship between the dependent and independent variables using graphs and tables, and relate these to the equation.",
    g:"write equations using dependent and independent variables"},
   {c:"6.AF.1", e:1, s:"Expressions with variables",
    t:"Define and use multiple variables when writing expressions to represent real-world and other mathematical problems, and evaluate them for given values.",
    g:"write and evaluate expressions with variables"},
   {c:"6.AF.2", e:1, s:"Substitution",
    t:"Demonstrate which values from a specified set, if any, make the equation or inequality true. Use substitution to determine whether a given number in a specified set makes an equation or inequality true.",
    g:"use substitution to check whether a value makes an equation or inequality true"},
   {c:"6.AF.3", e:1, s:"One-step equations",
    t:"Solve equations of the form x + p = q, x − p = q, px = q, and x/p = q fluently for cases in which p, q and x are all nonnegative rational numbers. Represent real-world problems using equations of these forms and solve such problems.",
    g:"solve one-step equations"},
   {c:"6.AF.4", e:0, s:"Writing inequalities",
    t:"Write an inequality of the form x > c, x ≥ c, x < c, or x ≤ c, where c is a rational number, to represent a constraint or condition in a real-world or other mathematical problem. Explain that inequalities have infinitely many solutions and how to represent solutions on a number line diagram.",
    g:"write inequalities for real-world situations and show them on a number line"},
   {c:"6.AF.5", e:1, s:"Coordinate plane",
    t:"Solve real-world and other mathematical problems by graphing points with rational number coordinates on a coordinate plane. Include the use of coordinates and absolute value to find distances between points with the same first coordinate or the same second coordinate.",
    g:"locate points and find distances on the coordinate plane"},
   {c:"6.GM.1", e:0, s:"Unit conversions",
    t:"Convert between measurement systems (Customary to metric and metric to Customary) given the conversion factors, and use these conversions in solving real-world problems.",
    g:"convert between customary and metric units"},
   {c:"6.GM.2", e:0, s:"Angle sums",
    t:"Apply the sums of interior angles of triangles and quadrilaterals to solve real-world and mathematical problems.",
    g:"use angle sums to find missing angles in triangles and quadrilaterals"},
   {c:"6.GM.3", e:0, s:"Area of complex shapes",
    t:"Find the area of complex shapes composed of polygons by composing or decomposing into simple shapes; apply this technique to solve real-world and other mathematical problems.",
    g:"find the area of complex shapes by breaking them into simple shapes"},
   {c:"6.GM.4", e:1, s:"Volume",
    t:"Find the volume of a right rectangular prism with fractional edge lengths using unit cubes of the appropriate unit fraction edge lengths (e.g., using technology or concrete materials) and show that the volume is the same as would be found by multiplying the edge lengths of the prism. Apply the formulas V = lwh and V = Bh to find volumes of right rectangular prisms with fractional edge lengths to solve real-world and other mathematical problems.",
    g:"find the volume of rectangular prisms with fraction edge lengths"},
   {c:"6.DS.1", e:0, s:"Data displays",
    t:"Select, create, and interpret graphical representations of numerical data, including line plots, histograms, and box plots.",
    g:"create and interpret line plots, histograms, and box plots"},
   {c:"6.DS.2", e:1, s:"Statistical questions",
    t:"Formulate statistical questions; collect and organize the data (e.g., using technology), and display and interpret the data with graphical representations (e.g., using technology).",
    g:"write statistical questions and display the data"},
   {c:"6.DS.3", e:1, s:"Summarizing data",
    t:"Summarize numerical data sets in relation to their context in multiple ways, such as: reporting the number of observations; describing the attribute under investigation, how it was measured, and its units; determining measures of center (mean and/or median) and spread (range and interquartile range); describing overall patterns and striking deviations; and relating the choice of measures to the shape of the data and the context.",
    g:"find the mean, median, range, and IQR and explain what they show"}
  ],
  ela:[
   {c:"6.RC.1", e:1, s:"Inferences and evidence",
    t:"Analyze what a text says explicitly as well as draw inferences from the text through citing textual evidence.",
    g:"make inferences and support them with evidence from the text"},
   {c:"6.RC.2", e:1, s:"Theme",
    t:"Determine how a theme or central idea of a work of literature is conveyed through particular details; provide a detailed, objective summary of the text.",
    g:"determine a theme and explain how details develop it"},
   {c:"6.RC.3", e:1, s:"Story structure",
    t:"Analyze how a particular sentence, chapter, scene, or stanza fits into the overall structure of a work of literature and contributes to the development of the theme, characterization, setting, or plot.",
    g:"explain how one part of a story fits into the whole"},
   {c:"6.RC.4", e:0, s:"Comparing texts",
    t:"Compare and contrast works of literature in different forms or genres (e.g., stories and poems, historical novels, and fantasy stories) in terms of their approaches to similar themes and topics.",
    g:"compare how two texts treat a similar theme"},
   {c:"6.RC.5", e:0, s:"Central idea",
    t:"Determine how a central idea of a text is conveyed through particular details; provide an objective summary of the text.",
    g:"determine the central idea of a nonfiction text and summarize it"},
   {c:"6.RC.6", e:0, s:"How ideas develop",
    t:"Analyze in detail how a key individual, event, or idea is introduced, illustrated, and elaborated in a text (e.g., through examples or anecdotes).",
    g:"explain how an author introduces and develops an idea"},
   {c:"6.RC.7", e:1, s:"Author's purpose",
    t:"Determine an author's perspective or purpose in a text, and explain how it is conveyed in the text.",
    g:"determine an author's purpose or perspective and how it is shown"},
   {c:"6.RC.8", e:0, s:"Evaluating claims",
    t:"Trace and evaluate the argument and specific claims in a text, distinguishing claims that the author supports with reasons and evidence from claims that are not supported.",
    g:"tell supported claims from unsupported claims"},
   {c:"6.RC.9", e:0, s:"Information in different formats",
    t:"Integrate information presented in different media or formats (e.g., visually, quantitatively, verbally) to demonstrate a coherent understanding of a topic or issue.",
    g:"combine information from different formats to understand a topic"},
   {c:"6.RC.10", e:0, s:"Context clues",
    t:"Use context to determine or clarify the meaning of words and phrases.",
    g:"use context clues to figure out word meanings"},
   {c:"6.RC.11", e:0, s:"Word relationships",
    t:"Use the relationship between particular words (e.g., cause/effect, part/whole, item/category) to better understand individual words.",
    g:"use word relationships to understand words"},
   {c:"6.RC.12", e:0, s:"Connotation",
    t:"Distinguish among the connotations of words with similar denotations.",
    g:"explain the connotations of words with similar meanings"},
   {c:"6.RC.13", e:1, s:"Roots and affixes",
    t:"Use common, grade-appropriate Greek or Latin affixes and roots as clues to the meaning of a word (e.g., audience, auditory, audible).",
    g:"use Greek and Latin roots and affixes to figure out word meanings"},
   {c:"6.W.1", e:1, s:"Argument writing",
    t:"Write arguments in a variety of forms that introduce claim(s) using strategies such as textual analysis, comparison/contrast, and cause/effect; use an organizational structure to group related ideas; support claim(s) with clear reasons and relevant evidence from credible sources; establish and maintain a consistent style and tone; use transitions that clarify relationships among claims and reasons; and provide a concluding statement or section.",
    g:"write an argument supported by evidence"},
   {c:"6.W.2", e:1, s:"Informative writing",
    t:"Write informative compositions in a variety of forms that introduce a topic and organize ideas using strategies such as definition and classification; develop the topic with relevant facts, definitions, details, quotations, and examples from various sources; use transitions; include formatting, graphics, and multimedia when useful; choose precise language and content-specific vocabulary; maintain an appropriate style; and provide a concluding statement or section.",
    g:"write to inform using facts from a text"},
   {c:"6.W.3", e:1, s:"Narrative writing",
    t:"Write narrative compositions in a variety of forms that engage and orient the reader by developing an exposition; organize an event sequence that unfolds naturally and logically, using transitions to show shifts in time or setting; use narrative techniques such as dialogue, pacing, and description; use precise words, relevant descriptive details, and sensory language; and provide an ending that follows from the events.",
    g:"write a narrative with details that fit the story"},
   {c:"6.W.4", e:0, gen:"6.W.2", alt:1, s:"Writing process",
    t:"Apply the writing process to all formal writing including but not limited to argumentative, informative, and narrative: plan and develop, draft, and revise writing using appropriate reference materials; rewrite, try a new approach, and edit to produce writing that is clear and coherent with some guidance and support; and use technology to generate, produce, and publish writing.",
    g:"plan, draft, revise, and edit my writing"},
   {c:"6.W.5", e:1, gen:"6.W.2", alt:1, s:"Research",
    t:"Conduct research assignments and tasks to build knowledge about the research process and the topic under study: formulate a research question; gather relevant information from multiple sources and annotate sources; assess the credibility of each source; quote or paraphrase the information and conclusions of others; avoid plagiarism and provide basic bibliographic information; and present information, choosing from a variety of formats.",
    g:"research a question using credible sources and cite them"},
   {c:"6.W.6", e:1, s:"Grammar and usage",
    t:"Demonstrate command of English grammar and usage, focusing on pronouns (subject, object, possessive, and reflexive; pronoun-antecedent agreement; correcting vague pronouns) and usage (simple, compound, complex, and compound-complex sentences; recognizing sentence fragments and run-ons).",
    g:"use pronouns correctly and write complete sentences"},
   {c:"6.W.7", e:1, s:"Punctuation",
    t:"Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling, focusing on using punctuation (e.g., commas, parentheses, dashes) to set off nonrestrictive/parenthetical elements, and using semicolons to connect main clauses and colons to introduce a list or quotation.",
    g:"use commas, dashes, parentheses, semicolons, and colons correctly"},
   {c:"6.CC.1", e:1, gen:"6.CC.2", alt:1, s:"Collaborative discussions",
    t:"Engage effectively in a range of collaborative discussions (e.g., one-on-one, in groups, and teacher-led) on grade appropriate topics, texts, and issues, building on others' ideas and expressing personal ideas clearly.",
    g:"take part in discussions, build on others' ideas, and share my ideas clearly"},
   {c:"6.CC.2", e:1, s:"Questions with evidence",
    t:"Pose and respond to specific questions with elaboration and detail by making comments that contribute to the topic, text, or issue under discussion.",
    g:"ask and answer questions with detail and evidence"},
   {c:"6.CC.3", e:1, s:"Paraphrasing perspectives",
    t:"Review the key ideas expressed and demonstrate understanding of multiple perspectives through reflection and paraphrasing.",
    g:"paraphrase different perspectives on an idea"},
   {c:"6.CC.4", e:0, gen:"6.RC.9", alt:1, s:"Interpreting media",
    t:"Interpret information presented in diverse media and formats (e.g., visually, quantitatively, orally) and explain how it contributes to a topic, text, or issue under study.",
    g:"explain how information in different formats adds to a topic"},
   {c:"6.CC.5", e:0, gen:"6.RC.8", alt:1, s:"A speaker's argument",
    t:"Delineate a speaker's argument and specific claims, distinguishing claims that are supported by reasons and evidence from claims that are not.",
    g:"tell which of a speaker's claims are supported by evidence"},
   {c:"6.CC.6", e:0, gen:"6.CC.3", alt:1, s:"Presenting claims",
    t:"Present claims and findings, sequencing ideas logically and using pertinent descriptions, facts, and details to accentuate main ideas or themes. Use appropriate eye contact, adequate volume, and clear pronunciation.",
    g:"present my ideas in a logical order with facts and details"},
   {c:"6.CC.7", e:0, gen:"6.W.2", alt:1, s:"Multimedia presentations",
    t:"Develop engaging presentations that include multimedia components (e.g., graphics, images, music, sound) and visual displays in presentations to clarify information.",
    g:"use multimedia and visuals to make my presentation clear"},
   {c:"6.CC.8", e:1, gen:"6.RC.8", alt:1, s:"Evaluating media",
    t:"Use evidence to evaluate the accuracy of information presented in multiple media messages.",
    g:"use evidence to judge whether media messages are accurate"}
  ]
 }
 }
};
