/* =====================================================================
   WIN Portal standards list: Indiana Academic Standards (IAS), grades 5 and 6.

   These are the 2023 Indiana Academic Standards, adopted by the State Board
   in June 2023. They are the standards ILEARN assesses in 2025-26 and 2026-27.
   Official documents: https://www.in.gov/doe/students/indiana-academic-standards/

   HOW TO EDIT (no coding needed):
   - Each standard is one { ... } line group.
       c  = the code, exactly as IDOE writes it (for example "5.CA.3")
       e  = 1 if it is an essential standard, otherwise 0
       s  = short name teachers and students see on the dashboard
       t  = the standard, in brief
       g  = the student learning target, finishing "I can ..."
       gen = (grade 5 only) which question generator writes practice for it.
             Leave gen alone if you only change c, s, t, or g.
   - Keep the commas and quotation marks. Save, then refresh the builder.
   ===================================================================== */
window.WIN_STANDARDS = {
 framework: "Indiana Academic Standards (2023)",
 /* Set review to "" after someone checks a grade's list against IDOE's documents. */
 review: {
  "5": "Grade 5 codes and wording were entered from the 2023 standards and should be checked against IDOE's grade 5 documents.",
  "6": ""
 },
 grades: {
 "5": {
  math:[
   {c:"5.NS.1", e:0, gen:"g5-compare", s:"Compare fractions and decimals",
    t:"Use a number line to compare and order fractions, mixed numbers, and decimals to thousandths; write results with >, =, and <",
    g:"compare and order fractions, mixed numbers, and decimals"},
   {c:"5.NS.2", e:0, gen:"g5-fracdiv", s:"Fractions as division",
    t:"Explain different interpretations of fractions: parts of a whole, parts of a set, and division of whole numbers",
    g:"explain a fraction as part of a whole, part of a set, or division"},
   {c:"5.NS.3", e:0, gen:"g5-place", s:"Place value patterns",
    t:"A digit in one place is 10 times what it represents in the place to its right and 1/10 of what it represents in the place to its left",
    g:"explain how the value of a digit changes from one place to the next"},
   {c:"5.NS.4", e:0, gen:"g5-round", s:"Rounding decimals",
    t:"Use place value to round decimals up to thousandths to any given place",
    g:"round decimals to any place"},
   {c:"5.NS.5", e:0, gen:"g5-percent", s:"Percents as parts of 100",
    t:"Understand, interpret, and model percents as part of a hundred",
    g:"explain and model percents as parts of 100"},
   {c:"5.CA.1", e:0, gen:"g5-divide", s:"Dividing whole numbers",
    t:"Find whole-number quotients and remainders with up to four-digit dividends and two-digit divisors",
    g:"divide whole numbers and explain the remainder"},
   {c:"5.CA.2", e:0, gen:"g5-decimal", s:"Decimal operations",
    t:"Add, subtract, multiply, and divide decimals to hundredths using models, place value, and properties",
    g:"add, subtract, multiply, and divide decimals"},
   {c:"5.CA.3", e:0, gen:"g5-fracadd", s:"Adding and subtracting fractions",
    t:"Add and subtract fractions and mixed numbers with unlike denominators, and use benchmark fractions to estimate",
    g:"add and subtract fractions with unlike denominators and check with an estimate"},
   {c:"5.CA.4", e:0, gen:"g5-fracmul", s:"Multiplying fractions",
    t:"Multiply a fraction by a whole number or a fraction using models and equations",
    g:"multiply fractions by whole numbers and by fractions"},
   {c:"5.CA.5", e:0, gen:"g5-fracdivide", s:"Dividing with unit fractions",
    t:"Divide a unit fraction by a whole number and a whole number by a unit fraction",
    g:"divide unit fractions and whole numbers"},
   {c:"5.CA.6", e:0, gen:"g5-multiply", s:"Multiplying whole numbers",
    t:"Multiply multi-digit whole numbers fluently using the standard algorithm",
    g:"multiply multi-digit whole numbers"},
   {c:"5.CA.7", e:0, gen:"g5-expr", s:"Expressions with parentheses",
    t:"Write and evaluate numerical expressions with parentheses",
    g:"write and evaluate expressions with parentheses"},
   {c:"5.G.1", e:0, gen:"g5-shapes", s:"Classifying shapes",
    t:"Classify two-dimensional figures in a hierarchy based on their properties",
    g:"sort triangles and quadrilaterals by their properties"},
   {c:"5.G.2", e:0, gen:"g5-coord", s:"Coordinate grid",
    t:"Graph and name points in the first quadrant of the coordinate plane",
    g:"graph and name points on a coordinate grid"},
   {c:"5.M.1", e:0, gen:"g5-convert", s:"Converting units",
    t:"Convert among different-sized units within the same measurement system",
    g:"convert units in the same measurement system"},
   {c:"5.M.2", e:0, gen:"g5-volume", s:"Volume",
    t:"Find the volume of right rectangular prisms using unit cubes, V = l × w × h, and V = B × h",
    g:"find the volume of rectangular prisms"},
   {c:"5.M.3", e:0, gen:"g5-area", s:"Area with fractions",
    t:"Find the area of rectangles with fractional side lengths",
    g:"find the area of rectangles with fraction side lengths"},
   {c:"5.DA.1", e:0, gen:"g5-lineplot", s:"Line plots with fractions",
    t:"Make and use line plots with fractional measurements to solve problems",
    g:"read line plots with fractions and solve problems with the data"}
  ],
  ela:[
   {c:"5.RC.1", e:0, gen:"6.RC.1", s:"Quoting to explain",
    t:"Quote accurately from a text to explain what it says explicitly and to draw inferences",
    g:"quote the text to explain what it says and what it suggests"},
   {c:"5.RC.2", e:0, gen:"6.RC.2", s:"Theme and summary",
    t:"Determine a theme from details in a story, play, or poem, and summarize the text",
    g:"find a theme using details and summarize the story"},
   {c:"5.RC.3", e:0, gen:"6.RC.3", s:"Story structure",
    t:"Explain how chapters, scenes, or stanzas fit together to give a story its structure",
    g:"explain how one part of a story fits with the rest"},
   {c:"5.RC.4", e:0, gen:"6.RC.4", s:"Comparing characters and stories",
    t:"Compare and contrast characters, settings, events, or stories on similar themes",
    g:"compare how characters or stories handle a similar idea"},
   {c:"5.RC.5", e:0, gen:"6.RC.5", s:"Main ideas",
    t:"Determine two or more main ideas of a nonfiction text, explain how details support them, and summarize",
    g:"find the main ideas of a nonfiction text and summarize it"},
   {c:"5.RC.6", e:0, gen:"6.RC.6", s:"How ideas connect",
    t:"Explain relationships between individuals, events, ideas, or concepts in a nonfiction text",
    g:"explain how people, events, or ideas in a text connect"},
   {c:"5.RC.7", e:0, gen:"6.RC.7", s:"Point of view",
    t:"Analyze an author's point of view and compare accounts of the same topic",
    g:"explain an author's point of view and how it shows"},
   {c:"5.RC.8", e:0, gen:"6.RC.8", s:"Reasons and evidence",
    t:"Explain how an author uses reasons and evidence to support points",
    g:"find the reasons and evidence an author uses to support a point"},
   {c:"5.RC.9", e:0, gen:"6.RC.9", s:"Information from several sources",
    t:"Integrate information from several texts or formats on the same topic",
    g:"combine information from different sources or formats"},
   {c:"5.RC.10", e:0, gen:"6.RC.10", s:"Context clues",
    t:"Use context to determine the meaning of words and phrases",
    g:"use context clues to figure out word meanings"},
   {c:"5.RC.11", e:0, gen:"6.RC.11", s:"Word relationships",
    t:"Use relationships between words (synonyms, antonyms, part/whole, cause/effect) to understand each word",
    g:"use word relationships to understand words"},
   {c:"5.RC.12", e:0, gen:"5.RC.12", s:"Figurative language",
    t:"Interpret figurative language, including similes, metaphors, and idioms",
    g:"explain what similes, metaphors, and idioms mean"},
   {c:"5.RC.13", e:0, gen:"6.RC.13", s:"Roots and affixes",
    t:"Use Greek and Latin affixes and roots to determine word meanings",
    g:"use Greek and Latin roots and affixes to figure out word meanings"},
   {c:"5.W.1", e:0, gen:"6.W.1", s:"Opinion writing",
    t:"Write opinion pieces that support a point of view with reasons and information",
    g:"write an opinion and support it with reasons from a text"},
   {c:"5.W.2", e:0, gen:"6.W.2", s:"Informative writing",
    t:"Write informative texts that explain a topic with facts and details",
    g:"explain a topic using facts from a text"},
   {c:"5.W.3", e:0, gen:"6.W.3", s:"Narrative writing",
    t:"Write narratives with descriptive details and a clear sequence of events",
    g:"write a narrative with details that fit the story"},
   {c:"5.W.6", e:0, gen:"5.W.6", s:"Grammar and usage",
    t:"Use verb tenses, correlative conjunctions, and adjectives and adverbs correctly",
    g:"use verb tenses, conjunctions, adjectives, and adverbs correctly"},
   {c:"5.W.7", e:0, gen:"5.W.7", s:"Punctuation",
    t:"Use commas, quotation marks, and apostrophes correctly",
    g:"use commas, quotation marks, and apostrophes correctly"},
   {c:"5.CC.2", e:0, gen:"6.CC.2", s:"Questions with evidence",
    t:"Pose and respond to specific questions, making comments that build on others' ideas",
    g:"ask and answer questions using details from the text"},
   {c:"5.CC.3", e:0, gen:"6.CC.3", s:"Summarizing points",
    t:"Summarize a speaker's or text's points and explain how each is supported",
    g:"summarize the points in a text and how they are supported"}
  ]
 },
 "6": {
  math:[
   {c:"6.NS.1", e:1, s:"Positive and negative numbers",
    t:"Use positive and negative numbers to represent quantities in real-world contexts; explain the meaning of 0",
    g:"use positive and negative numbers to describe real-world situations and explain what 0 means"},
   {c:"6.NS.2", e:0, s:"Opposites",
    t:"Opposite signs on the number line; the opposite of the opposite",
    g:"find opposites and explain where they sit on a number line"},
   {c:"6.NS.3", e:0, s:"Comparing rational numbers",
    t:"Compare and order rational numbers",
    g:"compare and order positive and negative numbers"},
   {c:"6.NS.4", e:1, s:"Fraction and decimal problems",
    t:"Solve real-world problems with positive fractions and decimals (one or two operations)",
    g:"solve real-world problems with fractions and decimals"},
   {c:"6.NS.5", e:1, s:"Order of operations",
    t:"Order of operations and properties with nonnegative rational numbers and exponents",
    g:"use the order of operations to evaluate expressions"},
   {c:"6.NS.6", e:0, s:"GCF and LCM",
    t:"GCF (to 100), LCM (to 12), and the distributive property",
    g:"find the GCF and LCM and use the distributive property"},
   {c:"6.NS.7", e:1, s:"Equivalent expressions",
    t:"Create and justify equivalent linear expressions",
    g:"write and check equivalent expressions"},
   {c:"6.NS.8", e:0, s:"Exponents",
    t:"Evaluate positive rational numbers with whole-number exponents",
    g:"evaluate numbers with exponents"},
   {c:"6.RP.1", e:1, s:"Fractions, decimals, percents",
    t:"Convert between fractions, decimals, and percents without a calculator",
    g:"convert between fractions, decimals, and percents without a calculator"},
   {c:"6.RP.2", e:0, s:"Unit rates",
    t:"Unit rates and rate language",
    g:"find and explain unit rates"},
   {c:"6.RP.3", e:0, s:"Ratio tables",
    t:"Tables of equivalent ratios",
    g:"complete tables of equivalent ratios"},
   {c:"6.RP.4", e:1, s:"Ratio and percent problems",
    t:"Solve ratio and rate problems (tables, tape diagrams, double number lines, equations)",
    g:"solve ratio, rate, and percent problems"},
   {c:"6.RP.5", e:1, s:"Dependent and independent variables",
    t:"Dependent and independent variables in proportional relationships",
    g:"write equations using dependent and independent variables"},
   {c:"6.AF.1", e:1, s:"Expressions with variables",
    t:"Write and evaluate expressions with variables",
    g:"write and evaluate expressions with variables"},
   {c:"6.AF.2", e:1, s:"Substitution",
    t:"Use substitution to find which values make an equation or inequality true",
    g:"use substitution to check whether a value makes an equation or inequality true"},
   {c:"6.AF.3", e:1, s:"One-step equations",
    t:"Solve one-step equations (x + p = q, x − p = q, px = q, x/p = q)",
    g:"solve one-step equations"},
   {c:"6.AF.4", e:0, s:"Writing inequalities",
    t:"Write inequalities for real-world constraints",
    g:"write inequalities for real-world situations"},
   {c:"6.AF.5", e:1, s:"Coordinate plane",
    t:"Coordinate plane: graph points and find distances",
    g:"locate points and find distances on the coordinate plane"},
   {c:"6.GM.1", e:0, s:"Unit conversions",
    t:"Convert between customary and metric units given conversion factors",
    g:"convert between customary and metric units"},
   {c:"6.GM.2", e:0, s:"Angle sums",
    t:"Interior angle sums of triangles and quadrilaterals",
    g:"use angle sums to find missing angles in triangles and quadrilaterals"},
   {c:"6.GM.3", e:0, s:"Area of composite shapes",
    t:"Area of composite shapes",
    g:"find the area of composite shapes"},
   {c:"6.GM.4", e:1, s:"Volume",
    t:"Volume of right rectangular prisms with fractional edges",
    g:"find the volume of rectangular prisms with fraction edge lengths"},
   {c:"6.DS.1", e:0, s:"Reading data displays",
    t:"Interpret line plots, histograms, and box plots",
    g:"read and interpret line plots, histograms, and box plots"},
   {c:"6.DS.2", e:1, s:"Statistical questions",
    t:"Statistical questions",
    g:"recognize and write statistical questions"},
   {c:"6.DS.3", e:1, s:"Mean, median, range, IQR",
    t:"Summarize data: mean, median, range, IQR",
    g:"find the mean, median, range, and IQR of a data set"}
  ],
  ela:[
   {c:"6.RC.1", e:1, s:"Inferences and evidence",
    t:"Analyze what a text says explicitly and draw inferences, citing textual evidence",
    g:"make inferences and support them with evidence from the text"},
   {c:"6.RC.2", e:1, s:"Theme",
    t:"Theme in literature and objective summary",
    g:"determine a theme and explain how details develop it"},
   {c:"6.RC.3", e:1, s:"Story structure",
    t:"How a sentence, scene, or paragraph fits the structure of literature",
    g:"explain how one part of a story fits into the whole"},
   {c:"6.RC.4", e:0, s:"Comparing texts",
    t:"Compare and contrast works of literature on similar themes",
    g:"compare how two texts treat a similar theme"},
   {c:"6.RC.5", e:0, s:"Central idea",
    t:"Central idea of a nonfiction text and objective summary",
    g:"determine the central idea of a nonfiction text and summarize it"},
   {c:"6.RC.6", e:0, s:"How ideas develop",
    t:"How a key individual, event, or idea is introduced and developed",
    g:"explain how an author introduces and develops an idea"},
   {c:"6.RC.7", e:1, s:"Author's purpose",
    t:"Author's perspective or purpose and how it is conveyed",
    g:"determine an author's purpose or perspective and how it is shown"},
   {c:"6.RC.8", e:0, s:"Evaluating claims",
    t:"Trace and evaluate claims; supported vs. unsupported",
    g:"tell supported claims from unsupported claims"},
   {c:"6.RC.9", e:0, s:"Information in different formats",
    t:"Integrate information from different media or formats",
    g:"combine information from different formats to understand a topic"},
   {c:"6.RC.10", e:0, s:"Context clues",
    t:"Use context to determine word meaning",
    g:"use context clues to figure out word meanings"},
   {c:"6.RC.11", e:0, s:"Word relationships",
    t:"Use word relationships (cause/effect, part/whole, item/category)",
    g:"use word relationships to understand words"},
   {c:"6.RC.12", e:0, s:"Connotation",
    t:"Connotations of words with similar denotations",
    g:"explain the connotations of words with similar meanings"},
   {c:"6.RC.13", e:1, s:"Roots and affixes",
    t:"Greek and Latin affixes and roots",
    g:"use Greek and Latin roots and affixes to figure out word meanings"},
   {c:"6.W.1", e:1, s:"Argument writing",
    t:"Write arguments",
    g:"write an argument supported by evidence"},
   {c:"6.W.2", e:1, s:"Informative writing",
    t:"Write informative compositions",
    g:"write to inform using facts from a text"},
   {c:"6.W.3", e:1, s:"Narrative writing",
    t:"Write narratives",
    g:"write a narrative with details that fit the story"},
   {c:"6.W.6", e:1, s:"Grammar and usage",
    t:"Grammar and usage: pronouns; sentence types, fragments, run-ons",
    g:"use pronouns correctly and write complete sentences"},
   {c:"6.W.7", e:1, s:"Punctuation",
    t:"Punctuation: nonrestrictive elements, semicolons, colons",
    g:"use commas, dashes, parentheses, semicolons, and colons correctly"},
   {c:"6.CC.2", e:1, s:"Questions with evidence",
    t:"Pose and respond to questions with elaboration and detail",
    g:"ask and answer questions with detail and evidence"},
   {c:"6.CC.3", e:1, s:"Paraphrasing perspectives",
    t:"Review key ideas and paraphrase multiple perspectives",
    g:"paraphrase different perspectives on an idea"}
  ]
 }
 }
};
